apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: native-ha-qm
spec:
  queueManager:
    availability:
      nativeHAGroups:    
        local:
          name: frankfurt
          tls:
            key:
              secretName: default-cert-copy
              items:
                - tls.key
                - tls.crt
        remotes: 
          - addresses: 
            - native-ha-qm-crr-ibm-mq-nhacrr-cp4i.apps.67c1cdecbf028633dde83ab1.ocp.techzone.ibm.com:443
            name: madrid
            trust: 
              - secret: 
                  secretName: letsencrypt-chain
                  items:
                    - ca.crt
