apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: common
spec:
  generators:
    - list:
        elements:
          - cluster: madrid
            clusterUrl: https://kubernetes.default.svc
          - cluster: frankfurt
            clusterUrl: https://api.67c1cda6bf028633dde83ab0.eu1.techzone.ibm.com:6443
  template:
    metadata:
      name: '{{cluster}}-common'
      namespace: openshift-gitops
      labels:
        group: applications
      annotations:
        argocd.argoproj.io/sync-wave: "50"
    spec:
      destination:
        namespace: cp4i
        server: '{{clusterUrl}}'
      project: default
      source:
        path: ./components/common/base
      syncPolicy:
        automated:
          prune: true
          selfHeal: true