apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - operators/operator-project.yaml
  - operands/operand-project.yaml
  - cp4i-argo-role.yaml
  - cp4i-argo-rb.yaml

  - common.yaml
  - operators/operators.yaml
  - operands/operands.yaml
 
patches:
- target:
    group: argoproj.io
    kind: Application
    labelSelector: group=applications
  patch: |-
    - op: add
      path: /spec/source/repoURL
      value: https://github.com/Nordic-MVP-GitOps-Repos/mq-crr.git
    - op: add
      path: /spec/source/targetRevision
      value: HEAD
- target:
    group: argoproj.io
    kind: ApplicationSet
  patch: |-
    - op: add
      path: /spec/template/spec/source/repoURL
      value: https://github.com/Nordic-MVP-GitOps-Repos/mq-crr.git
    - op: add
      path: /spec/template/spec/source/targetRevision
      value: HEAD