apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: native-ha-qm
spec:
  queueManager:
    availability:
      nativeHAGroups:
        local:
          name: us-east
          role: Recovery
          tls:
            key:
              secretName: default-cert-copy
              items:
                - tls.key
                - tls.crt
        remotes: 
          - addresses:  
            - native-ha-qm-crr-ibm-mq-nhacrr-cp4i.apps.67c1cda6bf028633dde83ab0.eu1.techzone.ibm.com:443
            name: europe-west
            trust: 
              - secret:
                  secretName: letsencrypt-chain   
                  items:
                  - ca.crt       
                