name: MQ-switchover-PR

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Change between live/recovery for MQ
        run: find envs -type f -name 'kustomization.yaml' -print0 | xargs -0 sed -i 's,variants/crr/live,SEDREPLACE,g;s,variants/crr/recovery,variants/crr/live,g;s,SEDREPLACE,variants/crr/recovery,g'  
      - name: Commit changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor.id }}@users.noreply.github.com"
          git checkout -b mq-crr-switchover
          git commit -am "MQ region switchover"
          git push --set-upstream origin mq-crr-switchover
      - name: Create PR
        run: gh pr create -B main -H mq-crr-switchover --title 'Switch region for MQ' --body 'Generated PR for switching between live and recovery regions'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
